name: Build RP2040 UF2

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build gcc-arm-none-eabi git python3-pip python3-venv libnewlib-arm-none-eabi
          pip3 install --upgrade pip

      - name: Clone pico-sdk
        run: |
          git clone --depth 1 https://github.com/raspberrypi/pico-sdk.git $GITHUB_WORKSPACE/pico-sdk
          cd $GITHUB_WORKSPACE/pico-sdk
          git submodule update --init --recursive

      - name: Configure build
        run: |
          mkdir -p build
          cd build
          export PICO_SDK_PATH=${GITHUB_WORKSPACE}/pico-sdk
          cmake -S .. -B . -G Ninja -DPICO_SDK_PATH=${GITHUB_WORKSPACE}/pico-sdk

      - name: Build
        run: |
          cd build
          ninja

      - name: Upload UF2 and ELF
        uses: actions/upload-artifact@v4
        with:
          name: rpzero-usb-uart-artifacts
          path: |
            build/**/*.uf2
            build/**/*.elf
